#cloud-config
packages:
  - curl
  - git
  - gzip
  - jq
  - tar
package_update: true
package_upgrade: false
runcmd:
  - udevadm trigger -c add -s block -p ID_VENDOR=HC -p ID_MODEL=Volume
  - export RUNNER_ALLOW_RUNASROOT=1
  - bash $MY_RUNNER_DIR/pre_runner_script.sh
  - $MY_RUNNER_DIR/config.sh --url "https://github.com/${MY_GITHUB_REPOSITORY}" --token "${MY_GITHUB_RUNNER_REGISTRATION_TOKEN}" --name "${MY_NAME}" --labels "${MY_NAME},hetzner" --no-default-labels
  - $MY_RUNNER_DIR/run.sh
write_files:
  - path: $MY_RUNNER_DIR/pre_runner_script.sh
    encoding: b64
    content: $MY_PRE_RUNNER_SCRIPT_BASE64
